version: '3.9'

services:
  sync:
    image: ghcr.io/multithefranky/ubiquityl:latest
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
